console.log("Hey What's Up");
console.log("文字列中のダブルクォーテーション(\")は注意が必要");
let productPrice = 1200;
const CONSUMPTION_TAX_RATE = 1.1;
let totalAmount = productPrice * CONSUMPTION_TAX_RATE;
console.log(totalAmount);
const numArray = [1, 2, 3, 4];
const stringArray = ["1", "2", "3", "4"];
console.log(numArray[0]);
console.log(stringArray[0]);
export {};
